<?php

return [
    'en' => [
        'nav_home' => 'Home', 'nav_menu' => 'Menu', 'nav_orders' => 'My Orders',
        'nav_favorites' => 'Favorites', 'nav_wishlist' => 'Wishlist', 'nav_profile' => 'Profile',
        'nav_login' => 'Log In', 'nav_register' => 'Register', 'nav_logout' => 'Log Out', 'nav_cart' => 'Cart',
        'nav_admin' => 'Admin Dashboard',
        'hero_title' => 'BASTA MASARAP', 'hero_tagline' => 'When it\'s delicious, it doesn\'t need much explanation.',
        'hero_cta' => 'Order Now', 'hero_view_menu' => 'View Full Menu',
        'section_featured' => 'Featured Dishes', 'section_popular' => 'Popular Right Now',
        'section_categories' => 'Browse by Category', 'section_reviews' => 'What Our Customers Say',
        'section_offers' => 'Today\'s Special', 'about_title' => 'Our Story',
        'about_body' => 'Basta Masarap started as a small carinderia with one promise: real Filipino home cooking, cooked with care, served without pretense. Every dish on our menu is a recipe passed down, perfected, and made for sharing.',
        'search_placeholder' => 'Search dishes...', 'sort_label' => 'Sort by', 'filter_category' => 'Category',
        'sort_popular' => 'Most Popular', 'sort_price_low' => 'Price: Low to High', 'sort_price_high' => 'Price: High to Low', 'sort_rating' => 'Highest Rated', 'sort_newest' => 'Newest',
        'add_to_cart' => 'Add to Cart', 'view_details' => 'View Details', 'out_of_stock' => 'Currently Unavailable',
        'like' => 'Like', 'dislike' => 'Dislike', 'add_favorite' => 'Add to Favorites', 'remove_favorite' => 'Remove Favorite',
        'add_wishlist' => 'Add to Wishlist', 'remove_wishlist' => 'Remove from Wishlist',
        'reviews' => 'Reviews', 'write_review' => 'Write a Review', 'your_rating' => 'Your Rating', 'submit_review' => 'Submit Review',
        'ingredients' => 'Ingredients', 'edited' => 'edited',
        'cart_title' => 'Your Cart', 'cart_empty' => 'Your cart is empty.', 'subtotal' => 'Subtotal', 'delivery_fee' => 'Delivery Fee', 'total' => 'Total',
        'checkout' => 'Checkout', 'continue_shopping' => 'Continue Shopping', 'remove' => 'Remove',
        'checkout_title' => 'Checkout', 'delivery_address' => 'Delivery Address', 'contact_number' => 'Contact Number', 'place_order' => 'Place Order',
        'order_confirmed_title' => 'Order Placed!', 'order_id' => 'Order ID', 'delivery_id' => 'Delivery ID',
        'order_history' => 'Order History', 'order_date' => 'Date', 'order_status' => 'Status', 'order_total' => 'Total', 'no_orders' => 'You haven\'t placed any orders yet.',
        'status_pending' => 'Pending', 'status_confirmed' => 'Confirmed', 'status_preparing' => 'Preparing',
        'status_out_for_delivery' => 'Out for Delivery', 'status_delivered' => 'Delivered', 'status_cancelled' => 'Cancelled',
        'login_title' => 'Welcome Back', 'username_or_email' => 'Username or Email', 'password' => 'Password',
        'register_title' => 'Create an Account', 'full_name' => 'Full Name', 'username' => 'Username', 'email' => 'Email',
        'confirm_password' => 'Confirm Password', 'already_have_account' => 'Already have an account?', 'no_account' => 'Don\'t have an account?',
        'profile_title' => 'My Profile', 'edit_profile' => 'Edit Profile', 'save_changes' => 'Save Changes',
        'member_since' => 'Member since', 'favorites_title' => 'My Favorite Dishes', 'wishlist_title' => 'My Wishlist',
        'no_favorites' => 'You haven\'t favorited any dishes yet.', 'no_wishlist' => 'Your wishlist is empty.',
        'footer_tagline' => 'Real Filipino food, cooked with love. BASTA MASARAP NGANI', 'footer_contact' => 'Contact Us', 'footer_hours' => 'Hours: 10:00 AM – 10:00 PM Daily',
        'footer_rights' => 'All rights reserved. (not really lol)',
    ],
    'fil' => [
        'nav_home' => 'Home', 'nav_menu' => 'Menu', 'nav_orders' => 'Mga Order Ko',
        'nav_favorites' => 'Paborito', 'nav_wishlist' => 'Wishlist', 'nav_profile' => 'Profile',
        'nav_login' => 'Mag-login', 'nav_register' => 'Mag-register', 'nav_logout' => 'Mag-logout', 'nav_cart' => 'Cart',
        'nav_admin' => 'Admin Dashboard',
        'hero_title' => 'BASTA MASARAP', 'hero_tagline' => 'Kapag masarap, hindi na kailangan ng maraming explanation.',
        'hero_cta' => 'Mag-order Na', 'hero_view_menu' => 'Tingnan ang Buong Menu',
        'section_featured' => 'Mga Featured na Ulam', 'section_popular' => 'Sikat Ngayon',
        'section_categories' => 'Mag-browse ayon sa Kategorya', 'section_reviews' => 'Sabi ng mga Customer Namin',
        'section_offers' => 'Special Ngayon', 'about_title' => 'Ang Kwento Namin',
        'about_body' => 'Nagsimula ang Basta Masarap bilang maliit na carinderia na may isang pangako: totoong lutong bahay ng Pilipino, niluto nang may pagmamahal, iserve nang walang arte. Bawat ulam sa menu namin ay recipe na pinasa, pinerpekto, at para sa pagsasaluhan.',
        'search_placeholder' => 'Maghanap ng ulam...', 'sort_label' => 'Ayusin ayon sa', 'filter_category' => 'Kategorya',
        'sort_popular' => 'Pinaka-sikat', 'sort_price_low' => 'Presyo: Mura muna', 'sort_price_high' => 'Presyo: Mahal muna', 'sort_rating' => 'Pinaka-mataas na Rating', 'sort_newest' => 'Pinakabago',
        'add_to_cart' => 'Idagdag sa Cart', 'view_details' => 'Tingnan ang Detalye', 'out_of_stock' => 'Wala Muna Ngayon',
        'like' => 'Gusto', 'dislike' => 'Ayaw', 'add_favorite' => 'Idagdag sa Paborito', 'remove_favorite' => 'Alisin sa Paborito',
        'add_wishlist' => 'Idagdag sa Wishlist', 'remove_wishlist' => 'Alisin sa Wishlist',
        'reviews' => 'Mga Review', 'write_review' => 'Mag-review', 'your_rating' => 'Rating Mo', 'submit_review' => 'I-submit ang Review',
        'ingredients' => 'Sangkap', 'edited' => 'na-edit',
        'cart_title' => 'Cart Mo', 'cart_empty' => 'Wala pang laman ang cart mo.', 'subtotal' => 'Subtotal', 'delivery_fee' => 'Delivery Fee', 'total' => 'Kabuuan',
        'checkout' => 'I-checkout', 'continue_shopping' => 'Magpatuloy sa Pag-order', 'remove' => 'Alisin',
        'checkout_title' => 'Checkout', 'delivery_address' => 'Delivery Address', 'contact_number' => 'Contact Number', 'place_order' => 'I-place ang Order',
        'order_confirmed_title' => 'Na-place na ang Order!', 'order_id' => 'Order ID', 'delivery_id' => 'Delivery ID',
        'order_history' => 'Kasaysayan ng Order', 'order_date' => 'Petsa', 'order_status' => 'Status', 'order_total' => 'Kabuuan', 'no_orders' => 'Wala ka pang na-order.',
        'status_pending' => 'Pending', 'status_confirmed' => 'Nakumpirma', 'status_preparing' => 'Inihahanda',
        'status_out_for_delivery' => 'Padating Na', 'status_delivered' => 'Naideliver Na', 'status_cancelled' => 'Kinansela',
        'login_title' => 'Maligayang Pagbabalik', 'username_or_email' => 'Username o Email', 'password' => 'Password',
        'register_title' => 'Gumawa ng Account', 'full_name' => 'Buong Pangalan', 'username' => 'Username', 'email' => 'Email',
        'confirm_password' => 'Kumpirmahin ang Password', 'already_have_account' => 'May account ka na?', 'no_account' => 'Wala pang account?',
        'profile_title' => 'Profile Ko', 'edit_profile' => 'I-edit ang Profile', 'save_changes' => 'I-save ang Changes',
        'member_since' => 'Miyembro simula', 'favorites_title' => 'Mga Paboritong Ulam Ko', 'wishlist_title' => 'Wishlist Ko',
        'no_favorites' => 'Wala ka pang na-favorite na ulam.', 'no_wishlist' => 'Walang laman ang wishlist mo.',
        'footer_tagline' => 'Totoong lutong Pinoy, niluto nang may pagmamahal.', 'footer_contact' => 'Makipag-ugnayan', 'footer_hours' => 'Oras: 10:00 AM – 10:00 PM Araw-araw',
        'footer_rights' => 'All rights reserved.',
    ],
];
